### ISSUE TITLE
ImportError: numpy._core.multiarray failed to import

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/mlperf-automations#6]
---

Migrated from https://github.com/mlcommons/mlperf-automations_archived/issues/46
Originally created by @anandhu-eng on *Mon, 18 Nov 2024 13:11:45 GMT*

---
```

Using MLCommons Inference source from '/home/anandhu/CM/repos/local/cache/c61b3360aaf84204/inference'
INFO:root:         ! cd /home/anandhu/CM/repos/local/cache/e96391f14ae64e0e
INFO:root:         ! call /home/anandhu/CM/repos/mlcommons@cm4mlops/script/get-dataset-coco2014/run.sh from tmp-run.sh
./download-coco-2014.sh -d /home/anandhu/CM/repos/local/cache/e96391f14ae64e0e/install -m 50

ImportError: _multiarray_umath failed to import
RuntimeError: CPU dispatcher tracer already initlized
Traceback (most recent call last):
  File "/home/anandhu/CM/repos/local/cache/c61b3360aaf84204/inference/text_to_image/tools/coco.py", line 5, in <module>
    import pandas as pd
  File "/home/anandhu/.local/lib/python3.10/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/anandhu/.local/lib/python3.10/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/home/anandhu/.local/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 17, in <module>
    import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]
ImportError: numpy._core.multiarray failed to import

CM error: Portable CM script failed (name = get-dataset-coco2014, return code = 256)

```

run command:
```
cm run script --tags=run,mlperf,accuracy,_coco2014 --result_dir=/home/anandhu/test_results
```

**Comment by anandhu-eng** [comment]
---

Migrated from https://github.com/mlcommons/mlperf-automations_archived/issues/46#issuecomment-2518449358
Originally created by @arjunsuresh on *Mon, 18 Nov 2024 13:20:11 GMT*

---
What's the pandas version here?

**Comment by anandhu-eng** [comment]
---

Migrated from https://github.com/mlcommons/mlperf-automations_archived/issues/46#issuecomment-2518449360
Originally created by @anandhu-eng on *Thu, 21 Nov 2024 14:20:27 GMT*

---
Hi @arjunsuresh , it was 2.2.3

I tried to reproduce in I9 system,

```
/home/anandhu/CM/repos/local/cache/c5f60ba1e1b144af/bertthreading/bin/python3 '/home/anandhu/CM/repos/local/cache/a25b6fc49f394682/inference/text_to_image/tools/accuracy_coco.py' --mlperf-accuracy-file '/home/anandhu/test_results/mlperf_log_accuracy.json' --caption-path '/home/anandhu/CM/repos/local/cache/a25b6fc49f394682/inference/text_to_image/coco2014/captions/captions_source.tsv' --compliance-images-path '/home/anandhu/test_results/images'  --ids-path '/home/anandhu/CM/repos/local/cache/fd96c918ddd64494/install/sample_ids.txt'  > '/home/anandhu/test_results/accuracy.txt'
Traceback (most recent call last):
  File "/home/anandhu/CM/repos/local/cache/a25b6fc49f394682/inference/text_to_image/tools/accuracy_coco.py", line 17, in <module>
    from fid.fid_score import (
  File "/home/anandhu/CM/repos/local/cache/a25b6fc49f394682/inference/text_to_image/tools/fid/fid_score.py", line 47, in <module>
    sys.path.insert("..", 0)
TypeError: 'str' object cannot be interpreted as an integer

```

I think the format is reverse: `sys.path.insert(index, path)`

**Comment by anandhu-eng** [comment]
---

Migrated from https://github.com/mlcommons/mlperf-automations_archived/issues/46#issuecomment-2518449353
Originally created by @arjunsuresh on *Mon, 18 Nov 2024 13:16:32 GMT*

---
numpy version issue?
We are using 1.26.4 [here](
https://github.com/GATEOverflow/mlperf_inference_test_submissions_v5.0/blob/main/open/MLCommons/measurements/gh_action-reference-gpu-pytorch-v2.5.1-cu124/stable-diffusion-xl/offline/pip_freeze.json#L22)

**Comment by anandhu-eng** [comment]
---

Migrated from https://github.com/mlcommons/mlperf-automations_archived/issues/46#issuecomment-2518449367
Originally created by @anandhu-eng on *Thu, 21 Nov 2024 14:21:15 GMT*

---
I think i have the old version of inference code, i saw a recent commit with the insert problem being fixed... let me try with latest pull

**Comment by anandhu-eng** [comment]
---

Migrated from https://github.com/mlcommons/mlperf-automations_archived/issues/46#issuecomment-2518449369
Originally created by @arjunsuresh on *Tue, 26 Nov 2024 13:26:30 GMT*

---
Hi @anandhu-eng is this issue still there?

**Comment by anandhu-eng** [comment]
---

Migrated from https://github.com/mlcommons/mlperf-automations_archived/issues/46#issuecomment-2533541430
Originally created by @anandhu-eng on *Wed, 11 Dec 2024 03:23:28 GMT*

---
Hi @arjunsuresh , let me test this today
